---
ID: 07b44fb1-828f-4f5c-b041-997cd1e0e74f
Parent: 5d6f9fe7-ead7-4aa8-bfee-a84adaa32efd
Template: 6d1cd897-1936-4a3a-a511-289a94c2a7b1
Path: /sitecore/system/Dictionary/ExperienceExplorer/General/Common/PageConfigurationRules
SharedFields:
- ID: 580c75a8-c01a-4580-83cb-987776ceb3af
  # Key
  Value: PageConfigurationRules
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150427T173426:635657528667681060Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Regler
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: PageConfigurationRules
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150427T174331:635657534119597253Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Regel
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: SeitenkonfigurationRegeln
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20130225T094929
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Rules
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150427T175226:635657539468690458Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: ルール
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: ページ設定ルール
