---
ID: a006a088-7028-46da-a034-cd47ce6fa015
Parent: 5d6f9fe7-ead7-4aa8-bfee-a84adaa32efd
Template: 6d1cd897-1936-4a3a-a511-289a94c2a7b1
Path: /sitecore/system/Dictionary/ExperienceExplorer/General/Common/Settings
SharedFields:
- ID: 580c75a8-c01a-4580-83cb-987776ceb3af
  # Key
  Value: Settings
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150427T173525:635657529251126242Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Indstillinger
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Indstillinger
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150427T174451:635657534912568081Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Einstellungen
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Einstellungen
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20131021T124140
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Settings
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150427T175341:635657540212911604Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: 設定
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: 設定
